#!/usr/bin/env bash
set -u -o pipefail
msg(){ printf '%s\n' "$*"; }
ok(){ printf '[OK] %s\n' "$*"; }
warn(){ printf '[!] %s\n' "$*" >&2; }
die(){ printf '[ERROR] %s\n' "$*" >&2; exit 1; }
need(){ command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"; }
for x in bash curl jq find sed awk sha256sum md5sum stat date mktemp sort tr head; do need "$x"; done
SECRETS_FILE="${PIXEL_UPLOADER_SECRETS:-$HOME/.config/pixel-uploader/secrets.env}"
if [[ -z "${BOT_TOKEN:-}" || -z "${CHAT_ID:-}" || -z "${PIXELDRAIN_API_KEY:-}" || -z "${TELEGRAPH_TOKEN:-}" ]]; then
 if [[ -f "$SECRETS_FILE" ]]; then perms="$(stat -c '%a' "$SECRETS_FILE" 2>/dev/null || stat -f '%Lp' "$SECRETS_FILE")"; [[ "$perms" == 600 ]] || die "Secrets file must have mode 600: $SECRETS_FILE"; source "$SECRETS_FILE"
 elif [[ -f "$HOME/.build_env" ]]; then perms="$(stat -c '%a' "$HOME/.build_env" 2>/dev/null || stat -f '%Lp' "$HOME/.build_env")"; [[ "$perms" == 600 ]] || die "~/.build_env must have mode 600"; source "$HOME/.build_env"; fi
fi
: "${BOT_TOKEN:?Set BOT_TOKEN}"; : "${CHAT_ID:?Set CHAT_ID}"; : "${PIXELDRAIN_API_KEY:?Set PIXELDRAIN_API_KEY}"; : "${TELEGRAPH_TOKEN:?Set TELEGRAPH_TOKEN}"
ROOT="${ANDROID_BUILD_TOP:-$(pwd)}"; OUT="$ROOT/out/target/product"; [[ -d "$OUT" ]] || die "Cannot find $OUT. Run from Android source tree or export ANDROID_BUILD_TOP."
choose(){ local max="$1" prompt="$2" value; while :; do read -r -p "$prompt" value || exit 1; if [[ "$value" =~ ^[0-9]+$ ]] && ((value>=1&&value<=max)); then printf '%s' "$value"; return; fi; warn "Enter 1-$max."; done; }
prop(){ local key="$1" f v; for f in "$DOUT/system/build.prop" "$DOUT/vendor/build.prop" "$DOUT/product/build.prop" "$DOUT/system/system/build.prop" "$DOUT/system/etc/prop.default" "$DOUT/vendor/etc/build.prop"; do [[ -f "$f" ]] || continue; v="$(sed -n "s/^${key}=//p" "$f" | head -n1 | tr -d '\r')"; [[ -n "$v" ]] && { printf '%s' "$v"; return; }; done; printf 'Unknown'; }
safe(){ printf '%s' "$1" | sed 's/[^A-Za-z0-9._-]/_/g;s/_\+/_/g;s/^_//;s/_$//'; }
html(){ printf '%s' "$1" | sed -e 's/\&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g'; }
file_type(){ local b="${1##*/}" l="${b,,}"; case "$l" in *.zip|*.ozip|*.zip.md5) echo ROM; return;; esac; if [[ "$l" =~ (^|[_-])vendor_kernel_boot([_-]|\.img$) ]]; then echo 'VENDOR KERNEL BOOT'; elif [[ "$l" =~ (^|[_-])vendor_boot([_-]|\.img$) ]]; then echo 'VENDOR BOOT'; elif [[ "$l" =~ (^|[_-])init_boot([_-]|\.img$) ]]; then echo 'INIT BOOT'; elif [[ "$l" =~ (^|[_-])vbmeta_system([_-]|\.img$) ]]; then echo 'VBMETA SYSTEM'; elif [[ "$l" =~ (^|[_-])vbmeta_vendor([_-]|\.img$) ]]; then echo 'VBMETA VENDOR'; elif [[ "$l" =~ (^|[_-])vbmeta([_-]|\.img$) ]]; then echo VBMETA; elif [[ "$l" =~ (^|[_-])dtbo([_-]|\.img$) ]]; then echo DTBO; elif [[ "$l" =~ (^|[_-])boot([_-]|\.img$) ]]; then echo BOOT; else echo FILE; fi; }
display_label(){ printf '%s' "$1"; }
mapfile -t DEVICES < <(find "$OUT" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort); ((${#DEVICES[@]})) || die 'No device output found.'
echo; echo 'Build outputs:'; for ((i=0;i<${#DEVICES[@]};i++)); do printf '  [%d] %s\n' "$((i+1))" "${DEVICES[$i]}"; done
n="$(choose "${#DEVICES[@]}" 'Select device: ')"; CODENAME="${DEVICES[$((n-1))]}"; DOUT="$OUT/$CODENAME"
ANDROID="$(prop ro.build.version.release)"; PATCH="$(prop ro.build.version.security_patch)"; BUILD="$(prop ro.build.id)"; DISPLAY="$(prop ro.build.display.id)"; DEVICE_DETECTED="$(prop ro.product.model)"; [[ "$DEVICE_DETECTED" == Unknown ]] && DEVICE_DETECTED="$(prop ro.product.name)"; [[ "$DEVICE_DETECTED" == Unknown ]] && DEVICE_DETECTED="$CODENAME"; msg "Device: $CODENAME | Android: $ANDROID | Build: $BUILD | SPL: $PATCH"
echo; echo 'Upload:'; echo '  [1] ROM'; echo '  [2] Images'; echo '  [3] ROM + Images'; MODE="$(choose 3 'Select: ')"; FILES=()
if ((MODE==1||MODE==3)); then mapfile -t ROMS < <(find "$DOUT" -maxdepth 1 -type f \( -iname '*.zip' -o -iname '*.ozip' -o -iname '*.zip.md5' \) | sort); ((${#ROMS[@]})) || die 'No ROM package found.'; echo; echo 'ROM packages:'; for ((i=0;i<${#ROMS[@]};i++)); do printf '  [%d] %s\n' "$((i+1))" "$(basename "${ROMS[$i]}")"; done; n="$(choose "${#ROMS[@]}" 'Select ROM: ')"; FILES+=("${ROMS[$((n-1))]}"); fi
if ((MODE==2||MODE==3)); then IMGS=(); while IFS= read -r -d '' f; do b="$(basename "$f")"; [[ "$b" =~ ^(boot|init_boot|dtbo|vendor_boot|vendor_kernel_boot|vbmeta|vbmeta_system|vbmeta_vendor)([-_].*)?\.img$ ]] && IMGS+=("$f"); done < <(find "$DOUT" -maxdepth 1 -type f -iname '*.img' -print0 | sort -z); ((${#IMGS[@]})) || die 'No supported images found.'; echo; echo 'Images:'; for ((i=0;i<${#IMGS[@]};i++)); do printf '  [%d] %s\n' "$((i+1))" "$(basename "${IMGS[$i]}")"; done; while :; do read -r -p 'Select images (e.g. 1 3 4): ' raw || exit 1; normalized="$(printf '%s' "$raw" | tr ',\t\r' '   ' | sed -E 's/[[:space:]]+/ /g;s/^ +//;s/ +$//')"; [[ "$normalized" =~ ^[0-9]+( [0-9]+)*$ ]] || { warn 'Use space-separated numbers, for example: 1 2 6'; continue; }; selected=(); while read -r number; do selected+=("$number"); done < <(printf '%s\n' "$normalized" | awk '{for(i=1;i<=NF;i++) print $i}'); good=1; seen=' '; for number in "${selected[@]}"; do ((number>=1&&number<=${#IMGS[@]})) || { good=0; break; }; [[ "$seen" == *" $number "* ]] && { good=0; break; }; seen+="$number "; done; ((good)) && break; warn "Enter valid image numbers from 1-${#IMGS[@]}, separated by spaces."; done; echo 'Selected images:'; for number in "${selected[@]}"; do FILES+=("${IMGS[$((number-1))]}"); printf '  - %s\n' "$(basename "${IMGS[$((number-1))]}")"; done; fi
read -r -p "Project name [${DISPLAY:-ROM}]: " PROJECT || exit 1; PROJECT="${PROJECT:-${DISPLAY:-ROM}}"; read -r -p 'Maintainer [Unknown]: ' AUTHOR || exit 1; AUTHOR="${AUTHOR:-Unknown}"; read -r -p "Device name [${DEVICE_DETECTED}]: " DEVICE_NAME || exit 1; DEVICE_NAME="${DEVICE_NAME:-$DEVICE_DETECTED}"; read -r -p 'Banner URL [optional]: ' BANNER_URL || exit 1; [[ -z "$BANNER_URL" || "$BANNER_URL" =~ ^https?:// ]] || die 'Banner URL must start with http:// or https://'
echo; echo 'Build Variant:'; echo '  [1] GApps Full'; echo '  [2] GApps Core'; echo '  [3] GApps Pico'; echo '  [4] Vanilla (No Google)'; echo '  [5] Vanilla + microG'; n="$(choose 5 'Select: ')"; case "$n" in 1) VARIANT='GApps Full'; VARIANT_TAG=GAPPS; GOOGLE_TAG=GAPPS-FULL; GOOGLE_SERVICES='GApps Full included'; GOOGLE_MODE=gapps;; 2) VARIANT='GApps Core'; VARIANT_TAG=GAPPS; GOOGLE_TAG=GAPPS-CORE; GOOGLE_SERVICES='GApps Core included'; GOOGLE_MODE=gapps;; 3) VARIANT='GApps Pico'; VARIANT_TAG=GAPPS; GOOGLE_TAG=GAPPS-PICO; GOOGLE_SERVICES='GApps Pico included'; GOOGLE_MODE=gapps;; 4) VARIANT=Vanilla; VARIANT_TAG=VANILLA; GOOGLE_TAG=NO-GMS; GOOGLE_SERVICES='No Google services'; GOOGLE_MODE=none;; 5) VARIANT='Vanilla + microG'; VARIANT_TAG=VANILLA; GOOGLE_TAG=MICROG; GOOGLE_SERVICES='microG included'; GOOGLE_MODE=microg;; esac
echo; echo 'Rooting method:'; echo '  [1] None'; echo '  [2] KSU'; echo '  [3] KSU Next'; echo '  [4] KSU Legacy'; echo '  [5] ReSukiSU'; echo '  [6] SukiSU'; n="$(choose 6 'Select: ')"; case "$n" in 1) ROOTM=None; ROOT_TAG='';; 2) ROOTM=KSU; ROOT_TAG=KSU;; 3) ROOTM='KSU Next'; ROOT_TAG=KSU-Next;; 4) ROOTM='KSU Legacy'; ROOT_TAG=KSU-Legacy;; 5) ROOTM=ReSukiSU; ROOT_TAG=ReSukiSU;; 6) ROOTM=SukiSU; ROOT_TAG=SukiSU;; esac
SUSFS=Disabled; if [[ "$ROOTM" != None ]]; then echo; echo 'SUSFS:'; echo '  [1] Without SUSFS'; echo '  [2] With SUSFS'; n="$(choose 2 'Select: ')"; [[ "$n" == 2 ]] && SUSFS=Enabled; fi
DATE="$(date +%Y-%m-%d)"; DISPLAY_DATE="$(date +%d-%m-%Y)"; RELEASE_ID="$(safe "$PROJECT")_${CODENAME}_$(safe "$VARIANT")_$(safe "$ROOTM")_$(safe "$SUSFS")_$DATE"
BUILD_TAGS="[$(safe "$PROJECT")]"; [[ -n "$DISPLAY" && "$DISPLAY" != Unknown && "$DISPLAY" != "$BUILD" ]] && BUILD_TAGS+=" [$DISPLAY]"; [[ -n "$BUILD" && "$BUILD" != Unknown ]] && BUILD_TAGS+=" [$BUILD]"; BUILD_TAGS+=" [Android $ANDROID] [$VARIANT_TAG] [$GOOGLE_TAG]"; [[ -n "$ROOT_TAG" ]] && BUILD_TAGS+=" [$ROOT_TAG]"; [[ "$SUSFS" == Enabled ]] && BUILD_TAGS+=' [SUSFS]'; BUILD_TAGS+=" [$DISPLAY_DATE]"
msg 'Checking credentials...'; curl --fail --silent --show-error --max-time 20 -u ":$PIXELDRAIN_API_KEY" https://pixeldrain.com/api/user/files >/dev/null || die 'Pixeldrain authentication failed. No files were uploaded.'; curl --fail --silent --show-error --max-time 20 "https://api.telegram.org/bot$BOT_TOKEN/getMe" | jq -e '.ok==true' >/dev/null || die 'Telegram bot authentication failed. No files were uploaded.'; curl --fail --silent --show-error --max-time 20 -X POST https://api.telegra.ph/getPageList -d "access_token=$TELEGRAPH_TOKEN" | jq -e '.ok==true' >/dev/null || die 'Telegraph authentication failed. No files were uploaded.'; ok 'Pixeldrain authentication OK'; ok 'Telegram bot authentication OK'; ok 'Telegraph authentication OK'
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT; MANIFEST="$TMP/files.tsv"; : > "$MANIFEST"
pixeldrain_upload(){ local f="$1" name="$2" response id; response="$(curl --fail-with-body -sS --max-time 3600 -u ":$PIXELDRAIN_API_KEY" -F "file=@$f;filename=$name" https://pixeldrain.com/api/file)" || return 1; id="$(jq -r '.id // empty' <<<"$response")"; [[ -n "$id" ]] || return 1; printf 'https://pixeldrain.com/u/%s' "$id"; }
echo; echo 'Uploading selected files to Pixeldrain...'; SUCCESS=0; for f in "${FILES[@]}"; do [[ -f "$f" ]] || { warn "Missing file: $f"; continue; }; base="$(basename "$f")"; ext="${base##*.}"; stem="${base%.*}"; if [[ "$base" == *.zip.md5 ]]; then name="${base%.zip.md5}_${RELEASE_ID}.zip.md5"; else name="${stem}_${RELEASE_ID}.${ext}"; fi; size="$(stat -c %s "$f" 2>/dev/null || stat -f %z "$f")"; md5="$(md5sum "$f" | awk '{print $1}')"; sha="$(sha256sum "$f" | awk '{print $1}')"; type="$(file_type "$f")"; if link="$(pixeldrain_upload "$f" "$name")"; then printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$base" "$name" "$type" "$size" "$md5" "$sha" "$link" >>"$MANIFEST"; SUCCESS=$((SUCCESS+1)); ok "$type: uploaded"; else warn "Pixeldrain upload failed: $base"; fi; done; ((SUCCESS>0)) || die 'No files were uploaded to Pixeldrain; Telegram publish cancelled.'
GUIDE=$'Installation Guide\n\n'; GUIDE+="Release: $PROJECT"$'\n'; GUIDE+="Device: $DEVICE_NAME ($CODENAME)"$'\n'; GUIDE+="Android: $ANDROID"$'\n'; GUIDE+="Security Patch: $PATCH"$'\n'; GUIDE+="Build Variant: $VARIANT"$'\n'; GUIDE+="Google Services: $GOOGLE_SERVICES"$'\n'; GUIDE+="Rooting: $ROOTM"$'\n'; GUIDE+="SUSFS: $SUSFS"$'\n'; GUIDE+="Maintainer: $AUTHOR"$'\n\n'; GUIDE+=$'Important:\n'; if [[ "$CODENAME" == bramble ]]; then GUIDE+=$'• This guide follows the current LineageOS installation flow for bramble.\n• Required stock firmware baseline: Android 14. Verify the device firmware before installation.\n'; else GUIDE+=$'• Use the device maintainer documentation for firmware and partition requirements.\n'; fi; GUIDE+=$'• Unlocking the bootloader wipes user data. Back up everything first.\n• Do not continue if a step fails.\n\n'; STEP=1; GUIDE+="$STEP. Boot to bootloader"$'\nadb -d reboot bootloader\nfastboot devices\n\n'; STEP=$((STEP+1))
if [[ "$CODENAME" == bramble ]]; then has_boot=0; has_dtbo=0; has_vendor_boot=0; boot_file=''; dtbo_file=''; vendor_boot_file=''; while IFS=$'\t' read -r original uploaded type size md5 sha link; do case "$type" in BOOT) has_boot=1; boot_file="$uploaded";; DTBO) has_dtbo=1; dtbo_file="$uploaded";; 'VENDOR BOOT') has_vendor_boot=1; vendor_boot_file="$uploaded";; esac; done < "$MANIFEST"; if ((has_boot||has_dtbo)); then GUIDE+="$STEP. Flash the additional partitions"$'\n'; ((has_boot)) && GUIDE+="fastboot flash boot $boot_file"$'\n'; ((has_dtbo)) && GUIDE+="fastboot flash dtbo $dtbo_file"$'\n'; GUIDE+=$'\n'; STEP=$((STEP+1)); GUIDE+="$STEP. Reboot to bootloader"$'\nfastboot reboot bootloader\n\n'; STEP=$((STEP+1)); fi; if ((has_vendor_boot)); then GUIDE+="$STEP. Install Lineage Recovery"$'\n'; GUIDE+="fastboot flash vendor_boot $vendor_boot_file"$'\n\n'; STEP=$((STEP+1)); GUIDE+="$STEP. Reboot to Recovery"$'\nUse the bootloader menu to select Recovery Mode.\n\n'; else GUIDE+="$STEP. Reboot to Recovery"$'\nUse the recovery provided by the ROM/device maintainer.\n\n'; fi; STEP=$((STEP+1)); else GUIDE+="$STEP. Flash the required image partitions"$'\n'; while IFS=$'\t' read -r original uploaded type size md5 sha link; do case "$type" in BOOT) GUIDE+="fastboot flash boot $uploaded"$'\n';; 'INIT BOOT') GUIDE+="fastboot flash init_boot $uploaded"$'\n';; DTBO) GUIDE+="fastboot flash dtbo $uploaded"$'\n';; 'VENDOR BOOT') GUIDE+="fastboot flash vendor_boot $uploaded"$'\n';; 'VENDOR KERNEL BOOT') GUIDE+="fastboot flash vendor_kernel_boot $uploaded"$'\n';; VBMETA) GUIDE+="fastboot flash vbmeta $uploaded"$'\n';; 'VBMETA SYSTEM') GUIDE+="fastboot flash vbmeta_system $uploaded"$'\n';; 'VBMETA VENDOR') GUIDE+="fastboot flash vbmeta_vendor $uploaded"$'\n';; esac; done < "$MANIFEST"; GUIDE+=$'\n'; STEP=$((STEP+1)); GUIDE+="$STEP. Reboot to Recovery"$'\nUse the recovery provided by the ROM/device maintainer.\n\n'; STEP=$((STEP+1)); fi
GUIDE+="$STEP. Factory reset for a clean installation"$'\nIn Recovery: Factory Reset -> Format data / factory reset -> confirm.\n\n'; STEP=$((STEP+1)); GUIDE+="$STEP. Sideload the ROM"$'\n'; rom_file="$(awk -F'\t' '$3=="ROM"{print $2; exit}' "$MANIFEST")"; if [[ -n "$rom_file" ]]; then GUIDE+=$'In Recovery: Apply update -> Apply from ADB.\n'; GUIDE+="On the computer: adb -d sideload /path/to/$rom_file"$'\n\n'; else GUIDE+=$'No ROM package was selected; install through the maintainer documented method.\n\n'; fi; STEP=$((STEP+1)); case "$GOOGLE_MODE" in gapps) GUIDE+="$STEP. Google Apps"$'\n'; GUIDE+="This build already includes $GOOGLE_SERVICES. Do not sideload another GApps package unless the ROM maintainer explicitly requires it."$'\n\n';; microg) GUIDE+="$STEP. Google services"$'\nmicroG is integrated in this build. Do not sideload a separate GApps package unless explicitly required.\n\n';; none) GUIDE+="$STEP. Google services"$'\nThis is a Vanilla build with no Google services. Do not sideload GApps unless explicitly compatible with this ROM and Android version.\n\n';; esac; STEP=$((STEP+1)); GUIDE+="$STEP. Reboot to system"$'\nIn Recovery: Reboot system now.\n\nNotes:\n• ADB sideload may appear to stop around 47% even when installation completed successfully.\n• If recovery reports a signature verification error, follow the ROM/recovery maintainer instructions before proceeding.\n• Root and SUSFS are build selections; no separate root package is required unless the maintainer says otherwise.\n'
GUIDE_JSON="$(jq -cn --arg text "$GUIDE" '[{tag:"pre",children:[$text]}]')"; TELEGRAPH_RESPONSE="$(curl -sS -X POST https://api.telegra.ph/createPage -d "access_token=$TELEGRAPH_TOKEN" --data-urlencode "title=Flash Guide - $PROJECT - $DISPLAY_DATE" --data-urlencode "author_name=$AUTHOR" --data-urlencode 'author_url=https://khaliq-repos.pages.dev/' --data-urlencode "content=$GUIDE_JSON")"; FLASH_GUIDE_URL="$(jq -r '.result.url // empty' <<<"$TELEGRAPH_RESPONSE" 2>/dev/null || true)"
TELEGRAM_MESSAGE=$'<b>New Release: '"$(html "$PROJECT for $CODENAME")"$'</b>\n\n'; TELEGRAM_MESSAGE+='<b>Device:</b> '"$(html "$CODENAME")"$'\n'; TELEGRAM_MESSAGE+='<b>Project:</b> '"$(html "$PROJECT")"$'\n'; TELEGRAM_MESSAGE+='<b>Android Version:</b> '"$(html "$ANDROID")"$'\n'; TELEGRAM_MESSAGE+='<b>Security Patch:</b> '"$(html "$PATCH")"$'\n'; TELEGRAM_MESSAGE+='<b>Build Variant:</b> '"$(html "$VARIANT_TAG")"$'\n'; TELEGRAM_MESSAGE+='<b>Google Services:</b> '"$(html "$GOOGLE_SERVICES")"$'\n'; TELEGRAM_MESSAGE+='<b>Release Date:</b> '"$(html "$DISPLAY_DATE")"$'\n'; TELEGRAM_MESSAGE+='<b>Maintainer:</b> '"$(html "$AUTHOR")"$'\n\n'; TELEGRAM_MESSAGE+='<b>Tag:</b> '"$(html "$BUILD_TAGS")"$'\n\n'; TELEGRAM_MESSAGE+='<b>Release Notes:</b>\n'; case "$GOOGLE_MODE" in gapps) TELEGRAM_MESSAGE+="$(html "✅ Google Apps (${VARIANT#GApps }) included")"$'\n'; TELEGRAM_MESSAGE+=$'✅ Google services integration\n';; microg) TELEGRAM_MESSAGE+=$'✅ Vanilla build\n✅ microG services included\n';; none) TELEGRAM_MESSAGE+=$'✅ Vanilla build\n✅ No Google services included\n';; esac; [[ "$ROOTM" != None ]] && TELEGRAM_MESSAGE+="$(html "✅ $ROOTM support included")"$'\n'; [[ "$SUSFS" == Enabled ]] && TELEGRAM_MESSAGE+=$'✅ SUSFS (Suspicious File System) enabled\n'; TELEGRAM_MESSAGE+=$'⚠️ Always backup your data before flashing\nFollow the flash guide for proper installation\n\n'; TELEGRAM_MESSAGE+='<b>Files Size Information:</b>\n'; while IFS=$'\t' read -r original uploaded type size md5 sha link; do mb="$(awk -v n="$size" 'BEGIN{if(n>=1073741824)printf "%.1f GB",n/1073741824;else printf "%.1f MB",n/1048576}')"; TELEGRAM_MESSAGE+="▫️ <b>$(html "$(display_label "$type")")</b> – $mb | MD5: <code>${md5:0:8}</code> | SHA: <code>${sha:0:8}</code>"$'\n'; done < "$MANIFEST"; TELEGRAM_MESSAGE+=$'\nClick the buttons below to download the files'
BUTTON_JSON_LINES=(); while IFS=$'\t' read -r original uploaded type size md5 sha link; do BUTTON_JSON_LINES+=("$(jq -cn --arg text "$(display_label "$type")" --arg url "$link" '{text:$text,url:$url}')"); done < "$MANIFEST"; KEYBOARD_JSON="$(printf '%s\n' "${BUTTON_JSON_LINES[@]}" | jq -sc '{inline_keyboard:([.[]] | to_entries | reduce .[] as $item ({rows:[],current:[]}; .current += [$item.value] | if (.current|length)==2 then .rows += [.current] | .current=[] else . end) | .rows + (if (.current|length)>0 then [.current] else [] end))}')"; [[ -n "$FLASH_GUIDE_URL" ]] && KEYBOARD_JSON="$(jq -c --arg url "$FLASH_GUIDE_URL" '.inline_keyboard += [[{text:"Flash Guide",url:$url}]]' <<<"$KEYBOARD_JSON")"; KEYBOARD_JSON="$(jq -c '.inline_keyboard += [[{text:"About Developer",url:"https://khaliq-repos.pages.dev/"}]]' <<<"$KEYBOARD_JSON")"; jq -e . >/dev/null <<<"$KEYBOARD_JSON" || die 'Generated Telegram keyboard is invalid JSON.'
send_result=''; if [[ -n "$BANNER_URL" ]]; then send_result="$(curl -sS -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendPhoto" -d chat_id="$CHAT_ID" --data-urlencode photo="$BANNER_URL" --data-urlencode caption="$TELEGRAM_MESSAGE" -d parse_mode=HTML --data-urlencode reply_markup="$KEYBOARD_JSON")"; if ! jq -e '.ok==true' >/dev/null <<<"$send_result"; then warn 'Banner send failed; falling back to text message.'; send_result="$(curl -sS -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id="$CHAT_ID" --data-urlencode text="$TELEGRAM_MESSAGE" -d parse_mode=HTML --data-urlencode reply_markup="$KEYBOARD_JSON")"; fi; else send_result="$(curl -sS -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id="$CHAT_ID" --data-urlencode text="$TELEGRAM_MESSAGE" -d parse_mode=HTML --data-urlencode reply_markup="$KEYBOARD_JSON")"; fi
if jq -e '.ok==true' >/dev/null <<<"$send_result"; then ok 'Telegram release published successfully.'; else warn "Telegram publish failed: $(jq -r '.description // "unknown error"' <<<"$send_result" 2>/dev/null || printf '%s' "$send_result")"; exit 1; fi
printf '%s\n' "$TELEGRAM_MESSAGE" >"$TMP/release-message.html"; printf '%s\n' "$KEYBOARD_JSON" >"$TMP/telegram-keyboard.json"; printf '%s\n' "$GUIDE" >"$TMP/flash-guide.txt"; msg "Release ID: $RELEASE_ID"
