#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

# Bias8145 multi-series release uploader
# Public script: secrets are NEVER stored here.

msg(){ printf '%s\n' "$*"; }; ok(){ printf '%s\n' "$*"; }; warn(){ printf '%s\n' "! $*" >&2; }; die(){ printf '%s\n' "ERROR: $*" >&2; exit 1; }
need(){ command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"; }
for x in curl jq find sed awk sha256sum md5sum stat date mktemp; do need "$x"; done
SECRETS_FILE="${PIXEL_UPLOADER_SECRETS:-$HOME/.config/pixel-uploader/secrets.env}"
if [[ -z "${BOT_TOKEN:-}" || -z "${CHAT_ID:-}" || -z "${PIXELDRAIN_API_KEY:-}" || -z "${TELEGRAPH_TOKEN:-}" ]]; then
  if [[ -f "$SECRETS_FILE" ]]; then perms="$(stat -c '%a' "$SECRETS_FILE" 2>/dev/null || stat -f '%Lp' "$SECRETS_FILE")"; [[ "$perms" == 600 ]] || die "Secrets file must have mode 600: $SECRETS_FILE"; source "$SECRETS_FILE"
  elif [[ -f "$HOME/.build_env" ]]; then perms="$(stat -c '%a' "$HOME/.build_env" 2>/dev/null || stat -f '%Lp' "$HOME/.build_env")"; [[ "$perms" == 600 ]] || die "~/.build_env must have mode 600"; source "$HOME/.build_env"; fi
fi
: "${BOT_TOKEN:?Set BOT_TOKEN}"; : "${CHAT_ID:?Set CHAT_ID}"; : "${PIXELDRAIN_API_KEY:?Set PIXELDRAIN_API_KEY}"; : "${TELEGRAPH_TOKEN:?Set TELEGRAPH_TOKEN}"
ROOT="${ANDROID_BUILD_TOP:-$(pwd)}"; OUT="$ROOT/out/target/product"; [[ -d "$OUT" ]] || die "Cannot find $OUT. Run from Android source tree or export ANDROID_BUILD_TOP."
choice(){ local max="$1" prompt="$2" v; while :; do read -r -p "$prompt" v || exit 1; [[ "$v" =~ ^[0-9]+$ ]] && ((v>=1&&v<=max)) && { printf '%s' "$v"; return; }; warn "Enter 1-$max."; done; }
prop(){ local k="$1" f v=''; for f in "$DOUT/system/build.prop" "$DOUT/vendor/build.prop" "$DOUT/product/build.prop" "$DOUT/system/system/build.prop" "$DOUT/system/etc/prop.default" "$DOUT/vendor/etc/build.prop"; do [[ -f "$f" ]] || continue; v="$(sed -n "s/^${k}=//p" "$f"|head -n1|tr -d '\r')"; [[ -n "$v" ]] && break; done; printf '%s' "${v:-Unknown}"; }
html(){ printf '%s' "$1"|sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/"/\&quot;/g'; }
safe(){ printf '%s' "$1"|sed 's/[^A-Za-z0-9._-]/_/g;s/__*/_/g;s/^_//;s/_$//'; }
mapfile -t DEVICES < <(find "$OUT" -mindepth 1 -maxdepth 1 -type d -printf '%f\n'|sort); ((${#DEVICES[@]}))||die 'No device output found.'
echo; echo 'Build outputs:'; i=1; for d in "${DEVICES[@]}"; do printf '  [%d] %s\n' "$i" "$d"; ((i++)); done
n=$(choice "${#DEVICES[@]}" 'Select device: '); CODENAME="${DEVICES[$((n-1))]}"; DOUT="$OUT/$CODENAME"
ANDROID="$(prop ro.build.version.release)"; PATCH="$(prop ro.build.version.security_patch)"; BUILD="$(prop ro.build.id)"; DISPLAY="$(prop ro.build.display.id)"; DETECTED_NAME="$(prop ro.product.model)"; [[ "$DETECTED_NAME" == Unknown ]]&&DETECTED_NAME="$(prop ro.product.name)"; [[ "$DETECTED_NAME" == Unknown ]]&&DETECTED_NAME="$CODENAME"
msg "Device: $CODENAME | Android: $ANDROID | Build: $BUILD | SPL: $PATCH"
echo; echo 'Upload:'; echo '  [1] ROM'; echo '  [2] Images'; echo '  [3] ROM + Images'; MODE=$(choice 3 'Select: '); FILES=()
if ((MODE==1||MODE==3)); then mapfile -t ROMS < <(find "$DOUT" -maxdepth 1 -type f \( -iname '*.zip' -o -iname '*.ozip' -o -iname '*.zip.md5' \)|sort); ((${#ROMS[@]}))||die 'No ROM package found.'; echo; echo 'ROM packages:'; i=1; for f in "${ROMS[@]}"; do printf '  [%d] %s\n' "$i" "$(basename "$f")"; ((i++)); done; n=$(choice "${#ROMS[@]}" 'Select ROM: '); FILES+=("${ROMS[$((n-1))]}"); fi
if ((MODE==2||MODE==3)); then IMGS=(); while IFS= read -r f; do b="$(basename "$f")"; [[ "$b" =~ ^(boot|init_boot|dtbo|vendor_boot|vendor_kernel_boot|vbmeta|vbmeta_system|vbmeta_vendor)([-_].*)?\.img$ ]]&&IMGS+=("$f"); done < <(find "$DOUT" -maxdepth 1 -type f -iname '*.img'|sort); ((${#IMGS[@]}))||die 'No supported images found.'; echo; echo 'Images:'; i=1; for f in "${IMGS[@]}"; do printf '  [%d] %s\n' "$i" "$(basename "$f")"; ((i++)); done; while :; do read -r -p 'Select images (e.g. 1 3 4): ' raw||exit 1; read -r -a sel <<< "${raw//,/ }"; good=1; seen=' '; for n in "${sel[@]}"; do [[ "$n" =~ ^[0-9]+$ ]]&&((n>=1&&n<=${#IMGS[@]}))||good=0; [[ "$seen" == *" $n "* ]]&&good=0; seen+="$n "; done; ((good&&${#sel[@]}>0))&&break; warn "Enter valid image numbers from 1-${#IMGS[@]}, separated by spaces."; done; for n in "${sel[@]}"; do FILES+=("${IMGS[$((n-1))]}"); done; echo 'Selected images:'; for n in "${sel[@]}"; do printf '  - %s\n' "$(basename "${IMGS[$((n-1))]}")"; done; fi
read -r -p "Project name [${DISPLAY:-ROM}]: " PROJECT||exit 1; PROJECT="${PROJECT:-${DISPLAY:-ROM}}"; read -r -p 'Maintainer [Unknown]: ' AUTHOR||exit 1; AUTHOR="${AUTHOR:-Unknown}"; read -r -p "Device name [${DETECTED_NAME}]: " DEVICE_NAME||exit 1; DEVICE_NAME="${DEVICE_NAME:-$DETECTED_NAME}"
echo; echo 'Variant:'; echo '  [1] GApps Full'; echo '  [2] GApps Core'; echo '  [3] GApps Pico'; echo '  [4] Vanilla'; echo '  [5] microG'; n=$(choice 5 'Select: '); VARIANT=('' 'GApps Full' 'GApps Core' 'GApps Pico' 'Vanilla' 'microG')[$n]
echo; echo 'Rooting method:'; echo '  [1] None'; echo '  [2] KSU'; echo '  [3] KSU Next'; echo '  [4] KSU Legacy'; echo '  [5] ReSukiSU'; echo '  [6] SukiSU'; n=$(choice 6 'Select: '); ROOTM=('' 'None' 'KSU' 'KSU Next' 'KSU Legacy' 'ReSukiSU' 'SukiSU')[$n]; SUSFS='Disabled'; if [[ "$ROOTM" != None ]]; then echo; echo 'SUSFS:'; echo '  [1] Without SUSFS'; echo '  [2] With SUSFS'; n=$(choice 2 'Select: '); [[ $n == 2 ]]&&SUSFS='Enabled'; fi
echo; echo 'Banner:'; echo '  [1] Without banner'; echo '  [2] Banner from URL'; BANNER_MODE=$(choice 2 'Select: '); BANNER_URL=''; if ((BANNER_MODE==2)); then read -r -p 'Banner URL: ' BANNER_URL||exit 1; [[ "$BANNER_URL" =~ ^https?:// ]]||die 'Banner URL must start with http:// or https://'; fi
DATE=$(date +%Y-%m-%d); RELEASE_ID="$(safe "$PROJECT")_${CODENAME}_$(safe "$VARIANT")_$(safe "$ROOTM")_$(safe "$SUSFS")_$DATE"
msg 'Checking credentials...'; curl --fail --silent --show-error --max-time 20 -u ":$PIXELDRAIN_API_KEY" https://pixeldrain.com/api/user/files >/dev/null||die 'Pixeldrain authentication failed. No files were uploaded.'; curl --fail --silent --show-error --max-time 20 "https://api.telegram.org/bot$BOT_TOKEN/getMe"|jq -e '.ok==true'>/dev/null||die 'Telegram bot authentication failed. No files were uploaded.'; curl --fail --silent --show-error --max-time 20 -X POST https://api.telegra.ph/getPageList -d "access_token=$TELEGRAPH_TOKEN"|jq -e '.ok==true'>/dev/null||die 'Telegraph authentication failed. No files were uploaded.'; ok 'Pixeldrain authentication OK'; ok 'Telegram bot authentication OK'; ok 'Telegraph authentication OK'
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT; :>"$TMP/files.tsv"
label(){ local b="$(basename "$1")" l="${b,,}"; case "$l" in *.zip|*.ozip|*.zip.md5)echo ROM;;boot*.img)echo BOOT;;init_boot*.img)echo 'INIT BOOT';;dtbo*.img)echo DTBO;;vendor_boot*.img)echo 'VENDOR BOOT';;vendor_kernel_boot*.img)echo 'VENDOR KERNEL BOOT';;vbmeta_system*.img)echo 'VBMETA SYSTEM';;vbmeta_vendor*.img)echo 'VBMETA VENDOR';;vbmeta*.img)echo VBMETA;;*)echo FILE;;esac; }
pd(){ local f="$1" name="$2" r id; r="$(curl --fail-with-body -sS --max-time 3600 -u ":$PIXELDRAIN_API_KEY" -F "file=@$f;filename=$name" https://pixeldrain.com/api/file)"||return 1; id="$(jq -r '.id//empty'<<<"$r")"; [[ -n "$id" ]]||return 1; printf 'https://pixeldrain.com/u/%s' "$id"; }
msg 'Uploading selected files to Pixeldrain...'
for f in "${FILES[@]}"; do [[ -f "$f" ]]||continue; b="$(basename "$f")"; ext="${b##*.}"; base="${b%.*}"; [[ "$b" == *.zip.md5 ]]&&name="${b%.zip.md5}_${RELEASE_ID}.zip.md5"||name="${base}_${RELEASE_ID}.${ext}"; size=$(stat -c %s "$f" 2>/dev/null||stat -f %z "$f"); md5=$(md5sum "$f"|awk '{print $1}'); sha=$(sha256sum "$f"|awk '{print $1}'); if link=$(pd "$f" "$name"); then printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$b" "$(label "$f")" "$size" "$md5" "$sha" "$link">>"$TMP/files.tsv"; ok "$(label "$f"): uploaded"; else warn "Pixeldrain upload failed: $b"; fi; done
[[ -s "$TMP/files.tsv" ]]||die 'No files were uploaded to Pixeldrain; Telegram publish cancelled.'
TELEGRAPH_URL=''; GUIDE_TEXT="Fastboot Flash Guide for $DEVICE_NAME ($CODENAME)\n\nProject: $PROJECT\nAndroid: $ANDROID\nBuild: $BUILD\nSecurity Patch: $PATCH\nVariant: $VARIANT\nRooting method: $ROOTM\nSUSFS: $SUSFS\nMaintainer: $AUTHOR\n\nSelected files:\n"; while IFS=$'\t' read -r b type size md5 sha link; do GUIDE_TEXT+="\n$type: $b\nPixeldrain: $link\nMD5: $md5\nSHA256: $sha\n"; done < "$TMP/files.tsv"; GUIDE_TEXT+="\nFlash instructions:\n1. Reboot to bootloader: fastboot reboot bootloader\n"; while IFS=$'\t' read -r b type size md5 sha link; do case "$type" in BOOT) GUIDE_TEXT+="2. Flash boot: fastboot flash --slot all boot $b\n";;'INIT BOOT') GUIDE_TEXT+="2. Flash init_boot: fastboot flash --slot all init_boot $b\n";;DTBO) GUIDE_TEXT+="2. Flash dtbo: fastboot flash --slot all dtbo $b\n";;'VENDOR BOOT') GUIDE_TEXT+="2. Flash vendor_boot: fastboot flash --slot all vendor_boot $b\n";;'VENDOR KERNEL BOOT') GUIDE_TEXT+="2. Flash vendor_kernel_boot: fastboot flash --slot all vendor_kernel_boot $b\n";;VBMETA) GUIDE_TEXT+="2. Flash vbmeta: fastboot --disable-verity --disable-verification flash vbmeta $b\n";;'VBMETA SYSTEM') GUIDE_TEXT+="2. Flash vbmeta_system: fastboot --disable-verity --disable-verification flash vbmeta_system $b\n";;'VBMETA VENDOR') GUIDE_TEXT+="2. Flash vbmeta_vendor: fastboot --disable-verity --disable-verification flash vbmeta_vendor $b\n";;esac; done < "$TMP/files.tsv"; while IFS=$'\t' read -r b type size md5 sha link; do [[ "$type" == ROM ]]&&GUIDE_TEXT+="3. Reboot to recovery: fastboot reboot recovery\n4. Apply ROM via ADB sideload: adb sideload $b\n"; done < "$TMP/files.tsv"; GUIDE_TEXT+="\nOnly the files selected for this release are listed above."
if response=$(curl --fail-with-body -sS -X POST https://api.telegra.ph/createPage --data-urlencode "access_token=$TELEGRAPH_TOKEN" --data-urlencode "title=$PROJECT - $DEVICE_NAME - $DATE" --data-urlencode "author_name=$AUTHOR" --data-urlencode 'author_url=https://github.com/Bias8145' --data-urlencode "content=[{\"tag\":\"h3\",\"children\":[\"$PROJECT\"]},{\"tag\":\"p\",\"children\":[\"Device: $DEVICE_NAME ($CODENAME)\"]},{\"tag\":\"p\",\"children\":[\"Android: $ANDROID | Build: $BUILD | SPL: $PATCH\"]},{\"tag\":\"p\",\"children\":[\"Variant: $VARIANT | Root: $ROOTM | SUSFS: $SUSFS\"]},{\"tag\":\"p\",\"children\":[\"Maintainer: $AUTHOR\"]},{\"tag\":\"pre\",\"children\":[\"$(printf '%s' "$GUIDE_TEXT"|sed 's/\\/\\\\/g;s/"/\\"/g;s/$/\\n/'|tr -d '\n')\"]}]" --data-urlencode 'return_content=false'); then TELEGRAPH_URL="$(jq -r '.result.url//empty'<<<"$response")"; fi
E_PROJECT=$(html "$PROJECT"); E_DEVICE=$(html "$DEVICE_NAME"); E_AUTHOR=$(html "$AUTHOR"); E_VARIANT=$(html "$VARIANT"); E_ROOT=$(html "$ROOTM"); E_SUSFS=$(html "$SUSFS")
MESSAGE="<b>New Release: $E_PROJECT</b>\n\nDevice: $E_DEVICE\nCodename: <code>$CODENAME</code>\nAndroid: $ANDROID\nBuild: $BUILD\nSecurity Patch: $PATCH\nVariant: $E_VARIANT\nRoot: $E_ROOT\nSUSFS: $E_SUSFS\nMaintainer: $E_AUTHOR\n\n<b>Files:</b>"; KEY='{"inline_keyboard":['; i=0
while IFS=$'\t' read -r b type size md5 sha link; do [[ $i -gt 0 ]]&&KEY+=','; mb=$(awk -v n="$size" 'BEGIN{printf "%.2f MB",n/1048576}'); MESSAGE+="\n\n<b>$type</b>\nName: <code>$(html "$b")</code>\nSize: $mb\nMD5: <code>$md5</code>\nSHA256: <code>$sha</code>"; KEY+="[{\"text\":\"Download $type\",\"url\":\"$link\"}]"; ((i++)); done<"$TMP/files.tsv"; [[ -n "$TELEGRAPH_URL" ]]&&KEY+=',[{"text":"Flash Guide","url":"'"$TELEGRAPH_URL"'"}]'; KEY+=',[{"text":"About Developer","url":"https://khaliq-repos.pages.dev/"}]'; KEY+=']}'; MESSAGE+="\n\nRelease published successfully."
if ((BANNER_MODE==2)); then if curl --fail --silent --show-error -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendPhoto" -F "chat_id=$CHAT_ID" --data-urlencode "photo=$BANNER_URL" --data-urlencode "caption=$MESSAGE" -F 'parse_mode=HTML' --data-urlencode "reply_markup=$KEY" >/dev/null; then ok 'Release published successfully with banner.'; else warn 'Banner could not be sent; publishing text release instead.'; curl --fail -sS -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -F "chat_id=$CHAT_ID" --data-urlencode "text=$MESSAGE" -F 'parse_mode=HTML' --data-urlencode "reply_markup=$KEY" >/dev/null||die 'Telegram publish failed.'; ok 'Release published successfully without banner.'; fi
else curl --fail -sS -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -F "chat_id=$CHAT_ID" --data-urlencode "text=$MESSAGE" -F 'parse_mode=HTML' --data-urlencode "reply_markup=$KEY" >/dev/null||die 'Telegram publish failed.'; ok 'Release published successfully.'; fi
